 excerpt_separator: <!--more-->

 sass:
  sass_dir: assets/_sass

 defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 
